language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.5
  - jruby-19mode
gemfile:
  - gemfiles/mongoid-3.1.gemfile
  - gemfiles/mongoid-4.0.gemfile
  - gemfiles/mongoid-5.1.gemfile
  - gemfiles/mongoid-6.0.gemfile
  - gemfiles/mongoid-7.0.gemfile
  - gemfiles/edge.gemfile
  - Gemfile

matrix:
  allow_failures:
    - gemfile: gemfiles/edge.gemfile
  fast_finish: true
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/mongoid-6.0.gemfile
    - rvm: 2.1
      gemfile: gemfiles/mongoid-7.0.gemfile
