language: ruby
rvm:
  - 2.1
  - 2.2
  - rbx-19mode
  - jruby-19mode
gemfile:
  - gemfiles/mongoid-3.1.gemfile
  - gemfiles/mongoid-4.0.gemfile
  - gemfiles/edge.gemfile
  - Gemfile

matrix:
  allow_failures:
    - gemfile: gemfiles/edge.gemfile
  fast_finish: true